# Generated by Django 5.2.1 on 2025-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='heading_activities',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
