# Generated by Django 5.2.1 on 2025-05-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_teacher_school_heading_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
