# Generated by Django 5.2.1 on 2025-05-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_nav_alter_notice_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('motto', models.CharField(max_length=300)),
            ],
        ),
    ]
